name: CompatHelper

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
        run: >-
          julia -e '
          using CompatHelper;
          CompatHelper.main() do;
            run(`julia --project=test -e "import Pkg; Pkg.instantiate(); Pkg.update()"`);
            run(`julia --project=docs -e "import Pkg; Pkg.instantiate(); Pkg.update()"`);
          end
          '
          
=======
        run: julia -e 'using CompatHelper; CompatHelper.main()'
>>>>>>> origin/master
